In [2]:
!pip3 install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 27.8 MB/s  0:00:00m0:00:010:01

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python3 -m pip install --upgrade pip


In [3]:
import numpy as np
import time

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
#execution performance
size = 10_000_000

#python list 
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list performance time = {end-start} seconds")

#np arrays
np_arr = np.array(py_list)
start1 = time.time()
sq_array = np_arr ** 2
end1 = time.time()
print(f"np array performance time = {end1-start1} seconds")

python list performance time = 0.801166296005249 seconds
np array performance time = 0.24643325805664062 seconds


In [7]:
import numpy as np

#create array from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,"prime"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [8]:
#create np arrays
import numpy as np

# 1. zeros() → array filled with 0
arr1 = np.zeros((2, 3), dtype="int64")
print("arr1 (zeros):")
print(arr1)
print("shape:", arr1.shape)
print()

# 2. ones() → array filled with 1
arr2 = np.ones((5,))
print("arr2 (ones):")
print(arr2)
print("shape:", arr2.shape)
print()

# 3. full() → array filled with specific value
arr3 = np.full((3, 4), 100)
print("arr3 (full with 100):")
print(arr3)
print("shape:", arr3.shape)
print()

# 4. eye() → identity matrix
arr4 = np.eye(3)
print("arr4 (identity matrix):")
print(arr4)
print("shape:", arr4.shape)
print()

# 5. arange() → range with step
arr5 = np.arange(0, 11, 2)
print("arr5 (arange):")
print(arr5)
print("shape:", arr5.shape)
print()

# 6. linspace() → evenly spaced numbers
arr6 = np.linspace(1, 100, 3)
print("arr6 (linspace):")
print(arr6)
print("shape:", arr6.shape)

arr1 (zeros):
[[0 0 0]
 [0 0 0]]
shape: (2, 3)

arr2 (ones):
[1. 1. 1. 1. 1.]
shape: (5,)

arr3 (full with 100):
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
shape: (3, 4)

arr4 (identity matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (3, 3)

arr5 (arange):
[ 0  2  4  6  8 10]
shape: (6,)

arr6 (linspace):
[  1.   50.5 100. ]
shape: (3,)


In [9]:
#properties

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)


(3, 3)
9
int64
2


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:")
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print("\nReshaped:")
print(reshaped, reshaped.shape)

flattened = arr.flatten()
print("\nFlattened:")
print(flattened, flattened.shape)

Original:
[[1 2 3]
 [4 5 6]] (2, 3)

Reshaped:
[[1 2]
 [3 4]
 [5 6]] (3, 2)

Flattened:
[1 2 3 4 5 6] (6,)


In [11]:
#normal indexing
arr = np.array([1,2,4,5,9])
print(arr[0])

#fancy indexing
idx = [0,2,4]
print(arr[idx])

#boolean indexing
print(arr[arr>2]) #2 se badi values ko print krne ke liye

1
[1 4 9]
[4 5 9]


In [12]:
#slicing
import numpy as np

# create array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Original Array:")
print(arr)
print()

# 1. Slice rows
print("First two rows:")
print(arr[0:2])
print()

# 2. Slice columns
print("Columns 1 to 2:")
print(arr[:, 1:3])
print()

# 3. Slice submatrix
print("Submatrix (rows 1-2, columns 1-2):")
print(arr[1:3, 1:3])
print()

# 4. Access single element
print("Element at row 2 column 1:")
print(arr[2,1])
print()

# 5. Select entire column
print("Second column:")
print(arr[:,1])
print()

# 6. Select entire row
print("Second row:")
print(arr[1,:])

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

First two rows:
[[10 20 30]
 [40 50 60]]

Columns 1 to 2:
[[20 30]
 [50 60]
 [80 90]]

Submatrix (rows 1-2, columns 1-2):
[[50 60]
 [80 90]]

Element at row 2 column 1:
80

Second column:
[20 50 80]

Second row:
[40 50 60]


In [ ]:
# data types
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr, arr.dtype) #int64 means 64-bit integer data type

[1 2 3 4 5] int64


In [15]:
arr1 = np.array([4+9j])
arr2 = np.array([3+0j])

print(arr1, arr1.dtype) #complex128 means complex number data type
print(arr2, arr2.dtype) #complex128 means complex number data type
print(arr1+arr2) #complex number addition

[4.+9.j] complex128
[3.+0.j] complex128
[7.+9.j]


# Axes in multidimentional arrays

In [ ]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.dtype) #int64 means 64-bit integer data

print(np.sum(arr2D)) #sum of all elements in the array
print(np.sum(arr2D, axis=0)) #sum of each column
print(np.sum(arr2D, axis=1)) #sum of each row

## 3D arrays

In [ ]:
arr3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3D, arr3D.dtype) #int64 means 64-bit integer data
print(arr3D)
print(np.sum(arr3D)) #sum of all elements in the array
print(np.sum(arr3D, axis=0)) #sum along the first axis (sum of corresponding elements in the two 2D arrays)
print(np.sum(arr3D, axis=1)) #sum along the second axis (sum of corresponding elements in the two 1D    arrays)
print(np.sum(arr3D, axis=2)) #sum along the third axis (sum of corresponding elements in the two 1D    arrays)